# This is a basic workflow to help you get started with Actions

name: Check PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
#   push:
#     branches: [ develop ]
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "gradle-check"
  check-pr:
    # The type of runner that the job will run on
    # https://github.com/actions/virtual-environments/
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
        
      # Setup Java 1.8
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Runs a set of commands using the runners shell
      - name: Gradle check
        run: |
          echo - Running gradle check
          ./gradlew check
          echo - Gradle check finished

