name: Publish Bintray

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Gradle check
        run: ./gradlew check
      
      - name: Publish to Bintray
        run: ./gradlew bintrayUpload
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
#          BINTRAY_GPG_PASSPHRASE: ${{secrets.BINTRAY_GPG_PASSPHRASE}}

      - name: Set PROJECT_VERSION
        run: |
          echo "▸ Set run permission."
          chmod +x scripts/version_name.sh
          echo "▸ Getting version name"
          PROJECT_VERSION=$(./scripts/version_name.sh)
          echo "▸ Variable PROJECT_VERSION set to: ${PROJECT_VERSION}"
          echo "▸ Adding PROJECT_VERSION variable with: $PROJECT_VERSION"
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          echo "▸ DONE"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: {{ env.PROJECT_VERSION }}
          release_name: Release {{ env.PROJECT_VERSION }}
          body: |
            - First Test Change
            - Second Test Change
          draft: false
          prerelease: false
